### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by q99266** [lx200916/CanaryConvertor#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x2f14a0]

goroutine 1 [running]:
main.toPostman(0xc00000c330, 0x28, 0x37335a, 0x2, 0x0, 0x0)
        /github/workspace/postman.go:305 +0x2d00
main.main.func1(0xc000058600, 0xc00000c330, 0x28)
        /github/workspace/HcyConverter.go:58 +0x1fb
github.com/urfave/cli/v2.(*App).RunContext(0xc00005f040, 0x3dbc90, 0xc0000100d8, 0xc000058040, 0x4, 0x4, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x714
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /github/workspace/HcyConverter.go:62 +0x1d8

**Comment by lx200916** [comment]
可否附上导出的文件以及CanaryApp版本信息方便排查?从Trace栈中好像没有特别有用的信息..(如果抓包记录中包含用户名或密码信息可脱敏或提供其他可复现场景)
